[project]
name = "project"
version = "0.1.0"
description = "Homework project with functions and BetterStack logging"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
]
